modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional Необходимо заполнить (быстрее всего создать лицуху Апачи в Гите, но ее нужно читать)

[[mods]]
modId="tms"
version="${file.jarVersion}" #mandatory Версию воткнем в файл jarVersion
displayName="The Merge Science" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="http://myurl.me/" #optional Нужно указать ссыль на табл с апгрейдами... chek
displayURL="https://github.com/Kan-Open/The-Merge-Science" #optional A URL for the "homepage" for this mod, displayed in the mod UI
logoFile="examplemod.png" #optional A file name (in the root of the mod JAR) containing a logo for display Нужно накалякать иконку мода в фотожопе

credits="Thanks for this mod goes to Java" #optional
authors="general concept of technology part: Alexey aka Wart1gon; general concept of magick part: Yuriy aka Kan Open"
description='''
The Merge Science is the mod for minecraft v.1.16.4+ This mod about magic and technology in The Cubicworld.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
